#!/bin/sh

echo "Running the tools analysis"

./mvnw pmd:pmd checkstyle:checkstyle

status=$?

if [ "$status" = 0 ] ; then
    echo "Tools found no problems"
    exit 0
else
    echo 1>&2 "Tools found violations"
    exit 1
fi